services:
  mariadb:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: parsonxam
      MARIADB_USER: parsonxam
      MARIADB_PASSWORD: parsonxam
    ports:
      - "3306:3306"
    volumes:
      - parsonxam_mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  parsonxam_mariadb_data:
